### ISSUE TITLE
http://thecodemine.org seems to be compromised

### ISSUE THREAD

**Issue by rinogo** [thecodemine/formwizard#47]
http://thecodemine.org is only loading malware.  I don't imagine this is the intent of the site! :/

**Comment by thecodemine** [comment]
Thanks for reporting this.

Since the formwizard is no longer maintained, the domain subscription was not prolonged. At that point I moved all the documentation to github to make it easily available for people who wanted to use the plugin or fork the code. 

However, in the process of moving the documentation, I forgot to remove the reference to the site. I have now removed the references.

Thanks again.
